# This is a basic workflow to help you get started with Actions

name: FreeRtos Win32-Demo Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sast-scan:
    # The type of runner that the job will run on
    runs-on: [windows, self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Baseline scanning
      - name: Synopsys Coverity Scan (Full Analysis)
        if: ${{ github.event_name != 'pull_request' }}
        shell: cmd
        run:  |
          pushd FreeRtos\Demo\WIN32-MSVC
          coverity scan --config coverity.win32-compliance.yaml --dir T:\GitHub\freertos-idir

      - name: Get Pull Request Changeset
        if: ${{ github.event_name == 'pull_request' }}
        id: changeset
        uses: jitterbit/get-changed-files@v1

      # Commands to perform changeset analysis  
      - name: Synopsys Coverity Scan (Changeset Analysis)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          CHANGESET_FILES: ${{ steps.changeset.outputs.added_modified }}
        shell: cmd
        run: |
          python .github\workflows\filefilter.py
          echo ------- PR Changeset -------
          type changeset-files.lst
          echo ----------------------------
          rem pushd FreeRtos\Demo\WIN32-MSVC
          cov-run-desktop --dir T:\GitHub\freertos-desktop-idir --setup
          cov-run-desktop --dir T:\GitHub\freertos-desktop-idir ^
              --strip-path %CD% --json-output-v7 coverity-results.json ^
              --ignore-uncapturable-inputs true ^
              --exit1-if-defects true ^
              --present-in-reference false @@changeset-files.lst
          if %ErrorLevel% equ 0  (set COVERITY_EC=0) else (set COVERITY_EC=1)
          echo Destkop-Run EC: %COVERITY_EC%
          python .github\workflows\patchstrippedfilepath.py 

      - name: Upload Analysis results
        uses: actions/upload-artifact@v3
        with:
          name: coverity-results
          path: |
             coverity-results.json
             coverity-results2.json
             D:\\Tools\\GitHub\\freertos-desktop-idir\\output\\his-metrics.mandatory-required.html
             D:\\Tools\\GitHub\\freertos-desktop-idir\\output\\callgraph-metrics
             D:\\Tools\\GitHub\\freertos-desktop-idir\\output\\deviations.txt
             D:\\Tools\\GitHub\\freertos-desktop-idir\\output\\deviations-warnings.txt



      - name: Coverity Pull Request Feedback
        uses: synopsys-sig/coverity-report-output-v7-json@v0.1.1 
        with:
          json-file-path: coverity-results2.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverity-url: http://localhost:8080
          coverity-project-name: FreeRTOS Compliance
          coverity-username: ${{ secrets.COV_USER }}
          coverity-password: ${{ secrets.COVERITY_PASSPHRASE }}


      - name: Coverity Result Code
        shell: cmd
        run: |
           echo $COVERITY_EC
           echo %COVERITY_EC%
           echo --------------
